#!/usr/bin/env python3

# Internet__ostname is used to determine if you have internet connectivity. You should
# use an ip address which is _very_ likely to respond.
internet_hostname = "1.1.1.1"

# Ip list is a list of ip-addresses you would like to check each time you test
# your internet connectivity. It could be a local server, an office host or
# whatever, really.
iplist   = ["10.202.102.147"]

# DNS will show you your local dns resolvers if set to True.
dns      =  True

# Most computers have a local or loopback interface. Myip will include this if set
# to True.
print_lo_if = False


# Check Python version.
import sys
sys.tracebacklimit = 0
assert sys.version_info >= (3, 4), "\n\nExiting, you must use Pyton 3.5 or newer.\n\n"
sys.tracebacklimit = 100


import os
import re
import subprocess
import netifaces as ifs
from requests import get


# You can add ip-addresses to check from command line. Just include as many as you want.
# Getting ip-address from ARGV:
for x in sys.argv[1:]:
    #print("arg=", x)
    regex = re.match(r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$", x)
    if regex:
        iplist.append(x)


# Define CLI colors:
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


# Small sub-routine to ping a certain ip address.
def pingip(ipaddress):
    pingresult = os.system("ping -c 1 -w 1 " + ipaddress + " > /dev/null")
    return (pingresult)


# Small sub-routine to check an ip-address and add appropriate colors.
def checkip(ipaddress):
    response = pingip(ipaddress)
    if response == 0:
        ipaddress = bcolors.OKGREEN + ipaddress + bcolors.ENDC
    else:
        ipaddress = bcolors.FAIL + ipaddress + bcolors.ENDC
    return (ipaddress)




# OK, Let's start the show..


# Print header
print("\nMy IP info:\n")


#  Ping Internet, check the response...
response = pingip(internet_hostname)
if response == 0:
    print("  Internet connection............................  " + bcolors.OKGREEN + "OK" + bcolors.ENDC)

    # Get my public ip-address:
    ip = get('https://api.ipify.org').text
    print('  My public IP address:..........................  {}'.format(ip))

    # Get my dns-name:
    #txt = subprocess.check_output(["/usr/bin/host", str(ip)])
    #dnsname = re.search(r"\S+$", str(txt))
    #print('  Public host name:..............................  ' + dnsname.group())

else:
    print("  Internet connection............................  " + bcolors.FAIL + "FAILED" + bcolors.ENDC)


# If additional ip-addresses are submitted:
for x in iplist:
    print("  Checking host .................................  "+ checkip(x) )


# Fetch IP info
for interface in ifs.interfaces():
    
    if len(ifs.ifaddresses(str(interface))) > 0:

        # Print interface name
        if bool(re.search('^lo', str(interface))) and not print_lo_if:
            continue
        print("\n  Network interface.............................. ",str(interface))

        # Print ip address
        my_if = ifs.ifaddresses(str(interface))
        my_if = my_if[2][0]
        print("  IP-Address..................................... ", str(my_if['addr']))

        # Print netmask
        print("  Netmask........................................ ", str(my_if['netmask']))


# Print default gateway
my_gw = ifs.gateways()['default'] 
print("\n  Active default-Gateway......................... ", checkip(my_gw[2][0]) + " (" + str(my_gw[2][1]) + ")")


# Print dns-servers
if dns:
    dns_servers = []

    # Read ip-addresses from resolv.conf
    ns_server = open("/etc/resolv.conf").read().split()
    for item in ns_server:
        if len( item.split(".") ) == 4:

            # If Entry is a localhost ip, we need to fetch real servers from nmcli
            if item == '127.0.1.1':

                txt = subprocess.check_output(["nmcli", "dev", "show"])
                lines = txt.splitlines()
                for line in lines: 
                    regex = re.match(r".*DNS.*", str(line))
                    if regex:
                        x = re.search(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", str(line))
                        dns_servers.append(x.group())
            else:
               dns_servers.append(item)

    # Print the servers we found
    already_done_once = False
    for entry in dns_servers:
        if already_done_once:
            print("                                                  ", entry)
        else:
            print("\n  DNS-server..................................... ", entry)
            already_done_once = True



print("\nDone.\n\n")
